export const deviation = [
  'Everyone has access to disruptor gun technology',
  'Everyone wears material impervious to projectile and energy weapons',
  'A long-dead figure from Earth Prime reigns dominant',
  'Subservient demihumans make up 95% of the population',
  'All humanoids have amphibious features',
  'Small carnivorous land dinosaurs dominate',
  'Tech suppression towers dot the landscape, rendering electronics useless',
  'An elite class of humans have teleportation tech, giving them supreme power',
  'Mammals never evolved past monkey-like creatures',
  'A vampiric virus keeps everyone shut in at night for fear of attack',
  'Women dominate in an absolute gynocracy',
  'Technology indistinguishable from magic has created a powerful “wizard” elite',
  'The hurricane of a millennium hovers over the coastline and floods everything',
  'Earth’s magnetic field has destabilized, leaving the surface a harsh wasteland',
  'A masked army of super soldiers imprisons anyone who falls out of line',
  'There is only one hermaphroditic gender of humans',
  'Petatons of plastic waste from another Earth fills the oceans and the land',
  'A single mob-like family controls every last aspect of humankind',
  'Everyone worships a flying superhero figure who uses ultratech to fool them',
  'Everyone is 150% larger by height and weight than normal',
  'Everyone is about a third of what would be a normal size',
  'Atmospheric oxygen levels are at about half of normal',
  'The burning of coal and oil has been accelerated and pollution is rampant',
  'Access to potable water has become an extreme challenge for survival globally',
  'Human fetuses are carried to term in large bovines and birthed ritualistically',
  'Most humans have been replaced by convincing androidal masters',
  'Society is dominated by a narcotic that confers psychic abilities and euphoria',
  'Civilization is devoted to building a wonder, and the process is destroying them',
  'A global virus has caused the dead to walk, and society has long adapted',
  'There is an earthquake or varying severity every 25 minutes',
  'An underclass of rudimentary robots serve as servants to society',
  'Everyone from a young age is trained to kill, leading to a rigidly martial society',
  'A virus has killed off all but a handful of humans on the planet',
  'There is no Moon, and Earth’s gravity is 50% stronger than normal',
  'Civilization is based entirely on The Hunt (for unwanted humans)',
  'A rogue military colonel from Earth Prime has set up an illicit empire',
]

export type Deviation = typeof deviation[number]
